# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

users = User.create([
  {name: 'Daniel Park', email: "daniel@flatiron.com"},
  {name: 'Liz Nicholson', email: "liz@flatiron.com"},
  {name: 'Ethan Ryan', email: "ethan@flatiron.com"},
  {name: 'Peter Kim', email: "peter@flatiron.com"}
  ])

recipes = Recipe.create([
  {name: 'Blueberry Walnut Salad', instructions: "In a large bowl, toss the salad greens with the blueberries, walnuts, and raspberry vinaigrette. Top with feta cheese to serve.", calories: 128, author_id: 1},
  {name: 'Reuben Sandwich', instructions: '1. Spread each slice of bread with thousand island dressing. Top 4 of the bread slices with sauerkraut, cheese and pastrami. Place remaining bread slices on sandwich. Spread margarine on the outsides of each sandwich. 2. Heat a large skillet over medium high heat. Grill until browned, then turn and grill until heated through, and cheese is melted.', calories: 198, author_id: 2}
  ])

ingredients = Ingredients.create([
  {name: 'Chicken Breast', type: 'meat'},
  {name: 'Ground Beef', type: 'meat'},
  {name: 'Bacon', type: 'meat'},
  {name: 'Sausage', type: 'meat'},
  {name: 'Ham', type: 'meat'},
  {name: 'Veal', type: 'meat'},
  {name: 'Beef Steak', type: 'meat'},
  {name: 'Hot Dog', type: 'meat'},
  {name: 'Pork Chops', type: 'meat'},
  {name: 'Chicken Thighs', type: 'meat'},
  {name: 'Ground Turkey', type: 'meat'},
  {name: 'Pork', type: 'meat'},
  {name: 'Turkey', type: 'meat'},
  {name: 'Pepperoni', type: 'meat'},
  {name: 'Whole Chicken', type: 'meat'},
  {name: 'Chicken Wings', type: 'meat'},
  {name: 'Chorizo', type: 'meat'},
  {name: 'Salami', type: 'meat'},
  {name: 'Ground Chicken', type: 'meat'},
  {name: 'Pork Ribs', type: 'meat'},
  {name: 'Venison', type: 'meat'},
  {name: 'Spam', type: 'meat'},
  {name: 'Lamb', type: 'meat'},
  {name: 'Pork Shoulder', type: 'meat'},
  {name: 'Roast Beef', type: 'meat'},
  {name: 'Bratwurst', type: 'meat'},
  {name: 'Proscuitto', type: 'meat'},
  {name: 'Chicken Roast', type: 'meat'},
  {name: 'Bologna', type: 'meat'},
  {name: 'Corned Beef', type: 'meat'},
  {name: 'Lamb Chops', type: 'meat'},
  {name: 'Ground Lamb', type: 'meat'},
  {name: 'Beef Ribs', type: 'meat'},
  {name: 'Duck', type: 'meat'},
  {name: 'Leg of Lamb', type: 'meat'},
  {name: 'Pork Belly', type: 'meat'},
  {name: 'Lamb Shank', type: 'meat'},
  {name: 'Garlic', type: 'Vegetable'},
  {name: 'Onion', type: 'Vegetable'},
  {name: 'Olive', type: 'Vegetable'},
  {name: 'Tomato', type: 'Vegetable'},
  {name: 'Potato', type: 'Vegetable'},
  {name: 'Carrot', type: 'Vegetable'},
  {name: 'Salad Greens', type: 'Vegetable'},
  {name: 'Basil', type: 'Vegetable'},
  {name: 'Parsley', type: 'Vegetable'},
  {name: 'Rosemary', type: 'Vegetable'},
  {name: 'Bell Pepper', type: 'Vegetable'},
  {name: 'Chili Pepper', type: 'Vegetable'},
  {name: 'Corn', type: 'Vegetable'},
  {name: 'Ginger', type: 'Vegetable'},
  {name: 'Mushroom', type: 'Vegetable'},
  {name: 'Broccoli', type: 'Vegetable'},
  {name: 'Spinach', type: 'Vegetable'},
  {name: 'Green Beans', type: 'Vegetable'},
  {name: 'Celery', type: 'Vegetable'},
  {name: 'Red Onion', type: 'Vegetable'},
  {name: 'Cilantro', type: 'Vegetable'},
  {name: 'Cucumber', type: 'Vegetable'},
  {name: 'Pickle', type: 'Vegetable'},
  {name: 'Dill', type: 'Vegetable'},
  {name: 'Avocado', type: 'Vegetable'},
  {name: 'Sweet Potato', type: 'Vegetable'},
  {name: 'Zucchini', type: 'Vegetable'},
  {name: 'Shallot', type: 'Vegetable'},
  {name: 'Mixed Vegetable', type: 'Vegetable'},
  {name: 'Cabbage', type: 'Vegetable'},
  {name: 'Asparagus', type: 'Vegetable'},
  {name: 'Cauliflower', type: 'Vegetable'},
  {name: 'Mint', type: 'Vegetable'},
  {name: 'Pumpkin', type: 'Vegetable'},
  {name: 'Kale', type: 'Vegetable'},
  {name: 'Scallion', type: 'Vegetable'},
  {name: 'Squash', type: 'Vegetable'},
  {name: 'Sun Dried Tomato', type: 'Vegetable'},
  {name: 'Horseradish', type: 'Vegetable'},
  {name: 'Sweet Corn', type: 'Vegetable'},
  {name: 'Beet', type: 'Vegetable'},
  {name: 'Butter', type: 'Dairy'},
  {name: 'Eggs', type: 'Dairy'},
  {name: 'Milk', type: 'Dairy'},
  {name: 'Parmesan', type: 'Dairy'},
  {name: 'Cheddar', type: 'Dairy'},
  {name: 'Cream', type: 'Dairy'},
  {name: 'Sour Cream', type: 'Dairy'},
  {name: 'Cream Cheese', type: 'Dairy'},
  {name: 'Mozzarella', type: 'Dairy'},
  {name: 'American Cheese', type: 'Dairy'},
  {name: 'Yogurt', type: 'Dairy'},
  {name: 'Evaporated Milk', type: 'Dairy'},
  {name: 'Whipped Cream', type: 'Dairy'},
  {name: 'Half & Half', type: 'Dairy'},
  {name: 'Monterey Jack Cheese', type: 'Dairy'},
  {name: 'Feta', type: 'Dairy'},
  {name: 'Cottage Cheese', type: 'Dairy'},
  {name: 'Ice Cream', type: 'Dairy'},
  {name: 'Goat Cheese', type: 'Dairy'},
  {name: 'ButterMilk', type: 'Dairy'},
  {name: 'Velveeta', type: 'Dairy'},
  {name: 'Ricotta', type: 'Dairy'},
  {name: 'Blue Cheese', type: 'Dairy'},
  {name: 'Provolone', type: 'Dairy'},
  {name: 'Gouda', type: 'Dairy'},
  {name: 'Pepper Jack', type: 'Dairy'},
  {name: 'Romano', type: 'Dairy'},
  {name: 'Brie', type: 'Dairy'},
  {name: 'Lemon', type: 'Fruit'},
  {name: 'Banana', type: 'Fruit'},
  {name: 'Apple', type: 'Fruit'},
  {name: 'Coconut', type: 'Fruit'},
  {name: 'Mango', type: 'Fruit'},
  {name: 'Lime', type: 'Fruit'},
  {name: 'Orange', type: 'Fruit'},
  {name: 'Pineapple', type: 'Fruit'},
  {name: 'Strawberries', type: 'Fruit'},
  {name: 'Raisin', type: 'Fruit'},
  {name: 'Blueberries', type: 'Fruit'},
  {name: 'Grapefruit', type: 'Fruit'},
  {name: 'Grape', type: 'Fruit'},
  {name: 'Prunes', type: 'Fruit'},
  {name: 'Nectarine', type: 'Fruit'},
  {name: 'Fig', type: 'Fruit'},
  {name: 'Peach', type: 'Fruit'},
  {name: 'Cranberries', type: 'Fruit'},
  {name: 'Raspberries', type: 'Fruit'},
  {name: 'Pear', type: 'Fruit'},
  {name: 'Charry', type: 'Fruit'},
  {name: 'Apricot', type: 'Fruit'},
  {name: 'Blackberries', type: 'Fruit'},
  {name: 'Date', type: 'Fruit'},
  {name: 'Watermelon', type: 'Fruit'},
  {name: 'Kiwi', type: 'Fruit'},
  {name: 'Mandarin', type: 'Fruit'},
  {name: 'Cantaloupe', type: 'Fruit'},
  {name: 'Plum', type: 'Fruit'},
  {name: 'Papaya', type: 'Fruit'},
  {name: 'Pomegranate', type: 'Fruit'},
  {name: 'Clementine', type: 'Fruit'},
  {name: 'Rhubarb', type: 'Fruit'},
  {name: 'Tangerine', type: 'Fruit'},
  {name: 'Currant', type: 'Fruit'},
  {name: 'Plantain', type: 'Fruit'},
  {name: 'Passion Fruit', type: 'Fruit'},
  {name: 'Persimons', type: 'Fruit'},
  {name: 'Red Pepper Flake', type: 'Spice'},
  {name: 'Cinnamon', type: 'Spice'},
  {name: 'Chive', type: 'Spice'},
  {name: 'Vanilla', type: 'Spice'},
  {name: 'Garlic Powder', type: 'Spice'},
  {name: 'Oregano', type: 'Spice'},
  {name: 'Paprika', type: 'Spice'},
  {name: 'Cayenne', type: 'Spice'},
  {name: 'Chili Powder', type: 'Spice'},
  {name: 'Cumin', type: 'Spice'},
  {name: 'Italian Seasoning', type: 'Spice'},
  {name: 'Thyme', type: 'Spice'},
  {name: 'Peppercorn', type: 'Spice'},
  {name: 'Nutmeg', type: 'Spice'},
  {name: 'Onion Powder', type: 'Spice'},
  {name: 'Curry Powder', type: 'Spice'},
  {name: 'Clove', type: 'Spice'},
  {name: 'Bay Leaf', type: 'Spice'},
  {name: 'Taco Seasoning', type: 'Spice'},
  {name: 'Sage', type: 'Spice'},
  {name: 'Ground Nutmeg', type: 'Spice'},
  {name: 'Chinese Five Spice', type: 'Spice'},
  {name: 'Allspice', type: 'Spice'},
  {name: 'Turmeric', type: 'Spice'},
  {name: 'Ground Coriander', type: 'Spice'},
  {name: 'Coriander', type: 'Spice'},
  {name: 'Cajun Seasoning', type: 'Spice'},
  {name: 'Steak Seasoning', type: 'Spice'},
  {name: 'Marjoram', type: 'Spice'},
  {name: 'Tarragon', type: 'Spice'},
  {name: 'Cardamom', type: 'Spice'},
  {name: 'Celery Seed', type: 'Spice'},
  {name: 'Chile Powder', type: 'Spice'},
  {name: 'Italian Herbs', type: 'Spice'},
  {name: 'Saffron', type: 'Spice'},
  {name: 'Caraway', type: 'Spice'},
  {name: 'Herbes de Provence', type: 'Spice'},
  {name: 'Italian Spice', type: 'Spice'},
  {name: 'Star Anise', type: 'Spice'},
  {name: 'Dill Seed', type: 'Spice'},
  {name: 'Canned Tuna', type: 'Fish'},
  {name: 'Salmon', type: 'Fish'},
  {name: 'Fish Fillets', type: 'Fish'},
  {name: 'Tilapia', type: 'Fish'},
  {name: 'Haddock', type: 'Fish'},
  {name: 'Grouper', type: 'Fish'},
  {name: 'Cod', type: 'Fish'},
  {name: 'Flounder', type: 'Fish'},
  {name: 'Anchovies', type: 'Fish'},
  {name: 'Tuna Steak', type: 'Fish'},
  {name: 'Rock Fish', type: 'Fish'},
  {name: 'Sardines', type: 'Fish'},
  {name: 'Smoked Salmon', type: 'Fish'},
  {name: 'Monkfish', type: 'Fish'},
  {name: 'Canned Salmon', type: 'Fish'},
  {name: 'Whitefish', type: 'Fish'},
  {name: 'Halibut', type: 'Fish'},
  {name: 'Trout', type: 'Fish'},
  {name: 'Mahi Mahi', type: 'Fish'},
  {name: 'Catfish', type: 'Fish'},
  {name: 'Sea Bass', type: 'Fish'},
  {name: 'Mackerel', type: 'Fish'},
  {name: 'Swordfish', type: 'Fish'},
  {name: 'Sole', type: 'Fish'},
  {name: 'Red Snapper', type: 'Fish'},
  {name: 'Pollock', type: 'Fish'},
  {name: 'Herring', type: 'Fish'},
  {name: 'Perch', type: 'Fish'},
  {name: 'Caviar', type: 'Fish'},
  {name: 'Pike', type: 'Fish'},
  {name: 'Bluefish', type: 'Fish'},
  {name: 'Lemon Sole', type: 'Fish'},
  {name: 'Eel', type: 'Fish'},
  {name: 'Carp', type: 'Fish'},
  {name: 'CuttleFish', type: 'Fish'},
  {name: 'Barramundi', type: 'Fish'},
  {name: 'Wheat Germ', type: 'Baking & Grains'},
  {name: 'Flour', type: 'Baking & Grains'},
  {name: 'Rice', type: 'Baking & Grains'},
  {name: 'Pasta', type: 'Baking & Grains'},
  {name: 'Bread', type: 'Baking & Grains'},
  {name: 'Baking Powder', type: 'Baking & Grains'},
  {name: 'Bread Flour', type: 'Baking & Grains'},
  {name: 'Baking Soda', type: 'Baking & Grains'},
  {name: 'Bread Crumbs', type: 'Baking & Grains'},
  {name: 'Cornstarch', type: 'Baking & Grains'},
  {name: 'Noodle', type: 'Baking & Grains'},
  {name: 'Rolled Oats', type: 'Baking & Grains'},
  {name: 'Yeast', type: 'Baking & Grains'},
  {name: 'Cracker', type: 'Baking & Grains'},
  {name: 'Quinoa', type: 'Baking & Grains'},
  {name: 'Pancake Mix', type: 'Baking & Grains'},
  {name: 'Flour Tortillas', type: 'Baking & Grains'},
  {name: 'Cornmeal', type: 'Baking & Grains'},
  {name: 'Chips', type: 'Baking & Grains'},
  {name: 'Saltines', type: 'Baking & Grains'},
  {name: 'Brown Rice', type: 'Baking & Grains'},
  {name: 'Popcorn', type: 'Baking & Grains'},
  {name: 'Self Rising Flour', type: 'Baking & Grains'},
  {name: 'Corn Tortillas', type: 'Baking & Grains'},
  {name: 'Stuffing Mix', type: 'Baking & Grains'},
  {name: 'Bixcuits', type: 'Baking & Grains'},
  {name: 'Couscous', type: 'Baking & Grains'},
  {name: 'Pie Crust', type: 'Baking & Grains'},
  {name: 'Pita', type: 'Baking & Grains'},
  {name: 'Cereal', type: 'Baking & Grains'},
  {name: 'Angel hair', type: 'Baking & Grains'},
  {name: 'Croutons', type: 'Baking & Grains'},
  {name: 'Lasagne', type: 'Baking & Grains'},
  {name: 'Ramen', type: 'Baking & Grains'},
  {name: 'Bqguette', type: 'Baking & Grains'},
  {name: 'Pizza Dough', type: 'Baking & Grains'},
  {name: 'Barley', type: 'Baking & Grains'},
  {name: 'Puff Pastry', type: 'Baking & Grains'},
  {name: 'Cake Mix', type: 'Baking & Grains'},
  {name: 'Bagel', type: 'Baking & Grains'},
  {name: 'Pretzel', type: 'Baking & Grains'},
  {name: 'Multigrain Bread', type: 'Baking & Grains'},
  {name: 'Crescent Roll Dough', type: 'Baking & Grains'},
  {name: 'Hot Dog Bun', type: 'Baking & Grains'},
  {name: 'Wheat', type: 'Baking & Grains'},
  {name: 'Ravioli', type: 'Baking & Grains'},
  {name: 'Gnocchi', type: 'Baking & Grains'},
  {name: 'Rye', type: 'Baking & Grains'},
  {name: 'Croissants', type: 'Baking & Grains'},
  {name: 'Vegetable Oil', type: 'Oil'},
  {name: 'Olive Oil', type: 'Oil'},
  {name: 'Peanut Oil', type: 'Oil'},
  {name: 'Cooking Spray', type: 'Oil'},
  {name: 'Shortening', type: 'Oil'},
  {name: 'Lard', type: 'Oil'},
  {name: 'Almond Oil', type: 'Oil'},
  {name: 'Grape Seed Oil', type: 'Oil'},
  {name: 'Shrimp', type: 'Seafood'},
  {name: 'Cockle', type: 'Seafood'},
  {name: 'Crawfish', type: 'Seafood'},
  {name: 'Crab', type: 'Seafood'},
  {name: 'Scallop', type: 'Seafood'},
  {name: 'Prawns', type: 'Seafood'},
  {name: 'Clam', type: 'Seafood'},
  {name: 'Lobster', type: 'Seafood'},
  {name: 'Octopus', type: 'Seafood'},
  {name: 'Calamari', type: 'Seafood'},
  {name: 'Squid', type: 'Seafood'},
  {name: 'Oyster', type: 'Seafood'},
  {name: 'Mussel', type: 'Seafood'},
  {name: 'Sugar', type: 'Added Sweetener'},
  {name: 'Honey', type: 'Added Sweetener'},
  {name: 'Confectioners Sugar', type: 'Added Sweetener'},
  {name: 'Maple Syrup', type: 'Added Sweetener'},
  {name: 'Syrup', type: 'Added Sweetener'},
  {name: 'Maple Syrup', type: 'Added Sweetener'},
  {name: 'Syrup', type: 'Added Sweetener'},
  {name: 'Molasses', type: 'Added Sweetener'},
  {name: 'Corn Syrup', type: 'Added Sweetener'},
  {name: 'Cream of Tartar', type: 'Seasoning'},
  {name: 'Bouillon', type: 'Seasoning'},
  {name: 'Ground Ginger', type: 'Seasoning'},
  {name: 'Sesame Seed', type: 'Seasoning'},
  {name: 'Apple Cider', type: 'Seasoning'},
  {name: 'Chili Sauce', type: 'Seasoning'},
  {name: 'Liquid Smoke', type: 'Seasoning'},
  {name: 'Balsamic Glaze', type: 'Seasoning'},
  {name: 'Hoisin Sauce', type: 'Seasoning'},
  {name: 'Vegetable Bouillon', type: 'Seasoning'},
  {name: 'Soy Sauce', type: 'Seasoning'},
  {name: 'Rice Wine', type: 'Seasoning'},
  {name: 'Fish Stock', type: 'Seasoning'},
  {name: 'Soy Milk', type: 'Dairy Alternative'},
  {name: 'Almond Milk', type: 'Dairy Alternative'},
  {name: 'Coconut Milk', type: 'Dairy Alternative'},
  {name: 'Hemp Milk', type: 'Dairy Alternative'},
  {name: 'Peas', type: 'Legume'},
  {name: 'Black Beans', type: 'Legume'},
  {name: 'Chickpeas', type: 'Legume'},
  {name: 'Lentil', type: 'Legume'},
  {name: 'Hummus', type: 'Legume'},
  {name: 'Soy Beans', type: 'Legume'},
  {name: 'Pinto Beans', type: 'Legume'},
  {name: 'Cannellini Beans', type: 'Legume'},
  {name: 'Navy Beans', type: 'Legume'},
  {name: 'Kidney Beans', type: 'Legume'},
  {name: 'Lima Beans', type: 'Legume'},
  {name: 'Green Beans', type: 'Legume'},
  {name: 'Peanut Butter', type: 'Nuts'},
  {name: 'Chestnut', type: 'Nuts'},
  {name: 'Almond', type: 'Nuts'},
  {name: 'Cashew', type: 'Nuts'},
  {name: 'Walnut', type: 'Nuts'},
  {name: 'Peanut', type: 'Nuts'},
  {name: 'Pecan', type: 'Nuts'},
  {name: 'Flax', type: 'Nuts'},
  {name: 'Pine Nut', type: 'Nuts'},
  {name: 'Pistachio', type: 'Nuts'},
  {name: 'Hazelnut', type: 'Nuts'},
  {name: 'Macadamia', type: 'Nuts'},
  {name: 'Mayonnaise', type: 'Condiments'},
  {name: 'Mustard', type: 'Condiments'},
  {name: 'Ketchup', type: 'Condiments'},
  {name: 'Vinegar', type: 'Condiments'},
  {name: 'Balsamic Vinegar', type: 'Condiments'},
  {name: 'Wine Vinegar', type: 'Condiments'},
  {name: 'Mirin', type: 'Condiments'},
  {name: 'Apple Cider Vinegar', type: 'Condiments'},
  {name: 'Fish Sauce', type: 'Condiments'},
  {name: 'Tomato Sauce', type: 'Sauces'},
  {name: 'Tomato Paste', type: 'Sauces'},
  {name: 'Chicken Gravy', type: 'Sauces'},
  {name: 'Pesto', type: 'Nuts'},
  {name: 'Beef Gravy', type: 'Nuts'}
  ])
